version: '3'
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://kafka:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      private: { }
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVERS: zk-node-1:2888:3888::1
    ports:
      - "2181:2181"
    networks:
      private: { }

  postgres:
    image: postgres:11.7
    environment:
      POSTGRES_DB: kafka-consumer
      POSTGRES_USER: kafka-consumer
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: kafka-consumer
    networks:
      - private
    ports:
      - "15432:5432"
networks:
  private:
    external: false
