version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      private: {}

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      SERVICE_NAME: zookeeper
      CONTAINER_NAME: zk-node-1
      ZOOKEEPER_SERVER_IDS: zk-node-1:1
      ZOOKEEPER_INSTANCES: zk-node-1
      ZOOKEEPER_ZK_NODE_1_HOST: zookeeper
      ZOOKEEPER_ZK_NODE_1_CLIENT_PORT: 2181
      ZOOKEEPER_ZK_NODE_1_PEER_PORT: 2888
      ZOOKEEPER_ZK_NODE_1_LEADER_ELECTION_PORT: 3888
    ports:
      - "2181:2181"
    networks:
      private: {}

  postgres:
    image: postgres:11.7
    environment:
      POSTGRES_DB: kafka-consumer
      POSTGRES_USER: kafka-consumer
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: kafka-consumer
    networks:
      - private
    ports:
      - "15432:5432"
networks:
  private:
    external: false
