on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16']
    name: run lint @ ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - run: go install golang.org/x/tools/cmd/goimports
    - run: goimports -w .
    - run: go mod tidy
    - name: Check goimports and go mod tidy
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]
    name: run tests @ ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - run: go test -v ./...
    - name: Gosec Security Scanner
      uses: securego/gosec@master

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]
    name: run build @ ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - run: go build -v ./...
